name: Add fix version to issue
on:
  workflow_call:
    secrets:
      JIRA_EMAIL:
        required: true
      JIRA_TOKEN:
        required: true
jobs:
  add_fix_version_to_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install @actions/github @actions/core node-fetch
      - uses: academicmerit/github-actions/actions/add_fix_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
